### ISSUE TITLE
Embedding in existing system

### ISSUE THREAD

**Issue by fslzia** [ElateralLtd/brandgility-embedded-api#10]
We are trying to embed api in our existing system. We want to use our own loadTemplate and Save buttons that will be outside iframe. 
Can someone please guide on how to do that?

What I understand is that we have to include lib.js file and import BrandgilityEmbeddedApi object. That will then get iframe contents. That object will be used to then invoke events. The lib.js file is built in ES6 while our system does not support that.

**Comment by ghost** [comment]
Please checkout [brandgility-embedded-demo](https://github.com/ElateralLtd/brandgility-embedded-demo). This app consumes the api and built as an example.

**Comment by fslzia** [comment]
@hhastekin-elateral  Thank you for sharing the link. This has really helped in making this work. We are able to now run save action but it only works in chrome as lib.js uses private vars which are an experimental feature and not available in firefox yet. Babel can be used but have not looked at that yet.

**Comment by sunstorymvp** [comment]
Hi @fslzia !

seem like you are using source code instead compiled version of it (tell me if I am wrong)

compiled package which you can consume from [npm](https://www.npmjs.com/package/@elateral/brandgility-embedded-api) should work in following browsers:
https://github.com/ElateralLtd/brandgility-embedded-api/blob/develop/browserslist

if it doesn't please let us know browser name and version. If you need to extend that list please mention which browser and version you need to support. thank you!

**Comment by fslzia** [comment]
Hi @sunstorymvp !

Yes, I was using source code directly. I have now tried compiled version downloaded from npm. Please note that we are not using node/npm in our project. So it is throwing error for module not defined. Can this work in standalone html page?

**Comment by sunstorymvp** [comment]
@fslzia we can bundle package as [umd](https://github.com/umdjs/umd) so it will work in browser as well as in node, will create PR soon. still it will be hosted on npm registry, but you can download and use it the same way you did it.

**Comment by sunstorymvp** [comment]
@fslzia fixed in `0.1.2`

**Comment by fslzia** [comment]
Thank you @sunstorymvp . UMD based version is working great in firefox too.
